name: validity
version: '0.4.0.4'
synopsis: Validity typeclass
description: ! 'For more info, see <https://github.com/NorfairKing/validity the readme>.


  Note: There are companion instance packages for this library:


  * <https://hackage.haskell.org/package/validity-aeson validity-aeson>


  * <https://hackage.haskell.org/package/validity-bytestring validity-bytestring>


  * <https://hackage.haskell.org/package/validity-containers validity-containers>


  * <https://hackage.haskell.org/package/validity-path validity-path>


  * <https://hackage.haskell.org/package/validity-scientific validity-scientific>


  * <https://hackage.haskell.org/package/validity-text validity-text>


  * <https://hackage.haskell.org/package/validity-time validity-time>


  * <https://hackage.haskell.org/package/validity-unordered-containers validity-unordered-containers>


  * <https://hackage.haskell.org/package/validity-uuid validity-uuid>


  * <https://hackage.haskell.org/package/validity-vector validity-vector>

'
category: Validity
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2016 Tom Sydney Kerckhove'
license: MIT
github: NorfairKing/validity
dependencies:
- base >=4.7 && <5
library:
  source-dirs: src
  exposed-modules:
  - Data.RelativeValidity
  - Data.Validity
  when:
  - condition: impl(ghc >=8.0.0)
    ghc-options: -Wno-redundant-constraints
